extends: recommended

rules:
  require-info-title:
    description: "info.title must be defined"
    severity: error
    given: $.info
    then:
      - field: title
        function: truthy

  require-info-version:
    description: "info.version must be defined"
    severity: error
    given: $.info
    then:
      - field: version
        function: truthy

  require-info-description:
    description: "info.description must be defined"
    severity: error
    given: $.info
    then:
      - field: description
        function: truthy

  require-x-konnect-slug:
    description: "info.x-konnect.slug must be defined"
    severity: error
    given: $.info["x-konnect"]
    then:
      - field: slug
        function: truthy

  require-x-konnect-attributes:
    description: "info.x-konnect.attributes must be defined"
    severity: error
    given: $.info["x-konnect"]
    then:
      - field: attributes
        function: truthy

  require-x-konnect-attributes-domain:
    description: "x-konnect.attributes.domain must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: domain
        function: truthy

  require-x-konnect-attributes-use-case:
    description: "x-konnect.attributes.use_case must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: use_case
        function: truthy

  require-x-konnect-attributes-audience:
    description: "x-konnect.attributes.audience must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: audience
        function: truthy

  require-x-konnect-attributes-data-type:
    description: "x-konnect.attributes.data_type must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: data_type
        function: truthy

  require-x-konnect-attributes-business-function:
    description: "x-konnect.attributes.business_function must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: business_function
        function: truthy

  require-x-konnect-attributes-workflow-stage:
    description: "x-konnect.attributes.workflow_stage must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: workflow_stage
        function: truthy

  require-x-konnect-attributes-integration-type:
    description: "x-konnect.attributes.integration_type must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: integration_type
        function: truthy

  require-x-konnect-attributes-access-level:
    description: "x-konnect.attributes.access_level must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: access_level
        function: truthy

  require-x-konnect-attributes-complexity-level:
    description: "x-konnect.attributes.complexity_level must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: complexity_level
        function: truthy

  require-x-konnect-attributes-industry-focus:
    description: "x-konnect.attributes.industry_focus must be defined"
    severity: error
    given: $.info["x-konnect"].attributes
    then:
      - field: industry_focus
        function: truthy