extends: recommended

rules:
  require-info-name:
    description: "info.name must be defined"
    severity: error
    given: $.info
    then:
      - field: name
        function: truthy

  require-info-title:
    description: "info.title must be defined"
    severity: error
    given: $.info
    then:
      - field: title
        function: truthy

  require-info-version:
    description: "info.version must be defined"
    severity: error
    given: $.info
    then:
      - field: version
        function: truthy

  require-info-description:
    description: "info.description must be defined"
    severity: error
    given: $.info
    then:
      - field: description
        function: truthy