name: Deploy APIs and Docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'apis/**'
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_konnect_system_account_access_token: ${{ secrets.KONNECT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./apis
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_APIS_STATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan
        working-directory: ./apis
        run: terraform plan -input=false -var-file=env/demo.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./apis
        run: terraform apply -auto-approve -input=false -var-file=env/demo.tfvars
